services:
  webserv:
    container_name: webserv
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - ./web/www/:/usr/share/nginx/html
    networks:
      - transcendence
    restart: always
    depends_on:
      - backend
    env_file:
    - .env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    networks:
      - transcendence
    restart: always
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16.2-alpine
    networks:
      - transcendence
    restart: always
    ports:
      - 5432
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

  setup:
    profiles:
      - setup
    build:
      context: monitor/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./monitor/setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./monitor/setup/lib.sh:/lib.sh:ro,Z
      - ./monitor/setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - transcendence
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: monitor/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitor/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - transcendence
    restart: unless-stopped

  logstash:
    build:
      context: monitor/logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitor/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./monitor/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - transcendence
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: monitor/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitor/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - transcendence
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    build:
      context: monitor/extensions/filebeat/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    user: root
    command:
      # Log to stderr.
      - -e
      - --strict.perms=false
    volumes:
      - ./monitor/extensions/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - transcendence
    depends_on:
      - elasticsearch

networks:
  transcendence:
    driver: bridge

volumes:
  database:
  elasticsearch:
